# Permalinks


# Site settings
title: Sandy Sage
description: "professional weblog and website of Sandy Sage, digital project and product manager"
intro: "I’m a software product manager. This is where I share my rantings, learnings, and other tidbits from my experience."
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
permalink: /:year/:title/
paginate: 10
paginate_path: "/page/:num/"
