# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Sandy Sage
tagline:             'Product Manager'
description:         'I’m a software product manager. This is where I share my rantings, learnings, and other tidbits from my experience.'
baseurl:             ''
paginate:            5

